@startuml
left to right direction
' Horizontal lines: -->, <--, <-->
' Vertical lines: ->, <-, <->
title Project Network Diagram

<style>
critical {
    BackGroundColor: red
}
</style>

map KickOff <<critical>> {
    0 => 0
    0! => 0!
}
map DI_1 {
    1 => 3
    5 => 7
}
KickOff --> DI_1

map DI_3 {
    1 => 8
    7 => 14
}
KickOff --> DI_3

map DI_6 <<critical>> {
    1 => 10
    1! => 10!
}
KickOff --> DI_6

map DI_7 {
    1 => 3
    8 => 10
}
KickOff --> DI_7

map DI_14 {
    1 => 3
    8 => 10
}
KickOff --> DI_14

map DI_19 {
    1 => 5
    13 => 17
}
KickOff --> DI_19

map DI_20 {
    1 => 5
    13 => 17
}
KickOff --> DI_20

map DI_22 {
    1 => 5
    13 => 17
}
KickOff --> DI_22

map DI_2 {
    4 => 13
    8 => 17
}
DI_1 --> DI_2

map DI_4 {
    9 => 11
    15 => 17
}
DI_3 --> DI_4

map DI_5 {
    9 => 11
    15 => 17
}
DI_3 --> DI_5

map DI_8 {
    11 => 14
    14 => 17
}
DI_6 --> DI_8
DI_7 --> DI_8

map DI_9 {
    11 => 15
    13 => 17
}
DI_6 --> DI_9
DI_7 --> DI_9

map DI_10 <<critical>> {
    11 => 17
    11! => 17!
}
DI_6 --> DI_10
DI_7 --> DI_10

map DI_11 {
    11 => 14
    14 => 17
}
DI_6 --> DI_11
DI_7 --> DI_11

map DI_12 {
    11 => 13
    15 => 17
}
DI_6 --> DI_12
DI_7 --> DI_12

map DI_13 {
    11 => 13
    15 => 17
}
DI_6 --> DI_13
DI_7 --> DI_13

map DI_15 {
    11 => 14
    14 => 17
}
DI_6 --> DI_15
DI_14 --> DI_15

map DI_16 {
    11 => 14
    14 => 17
}
DI_6 --> DI_16
DI_14 --> DI_16

map DI_17 <<critical>> {
    11 => 13
    11! => 13!
}
DI_6 --> DI_17
DI_14 --> DI_17

map DI_18 <<critical>> {
    14 => 17
    14! => 17!
}
DI_17 --> DI_18

map DI_21 {
    11 => 13
    15 => 17
}
DI_6 --> DI_21

map DI_TR <<critical>> {
    18 => 18
    18! => 18!
}
DI_2 --> DI_TR
DI_4 --> DI_TR
DI_5 --> DI_TR
DI_8 --> DI_TR
DI_9 --> DI_TR
DI_10 --> DI_TR
DI_11 --> DI_TR
DI_12 --> DI_TR
DI_13 --> DI_TR
DI_15 --> DI_TR
DI_16 --> DI_TR
DI_18 --> DI_TR
DI_19 --> DI_TR
DI_20 --> DI_TR
DI_21 --> DI_TR
DI_22 --> DI_TR

@enduml