@startwbs
!include ../metamodels/requirement-breakdown.iuml

goal("Optimize Waste Collection")

'Dumpster Infrastructure
requirement("Dumpster infrastructure")
function("Monitor dumpsters volume")

function("Open dumpsters\nwith smart-cards")

function("Collect and share data")

'Citizen App
requirement("Citizen app")
function("Consult dumpsters'\nvolume status")

function("Book extraordinary\nwaste disposal missions")

function("Notify issues")

'Trucks Routing
requirement("Trucks routing")
function("Plan ordinary waste\ndisposal missions")

function("Plan extraordinary waste\ndisposal missions")

function("Organize missions' route")

'Admin Dashboard
requirement("Admin dashboard")
function("Display collection\npoints' status")

function("Display trucks'\nreal-time position")

function("Display complaints")

legend left
    Blue = Goal
    Green = Requirements
    Yellow = Functions
    Red = Features
endlegend
@endwbs