@startwbs
!include ../metamodels/work-breakdown.iuml
!$title = AD

requirement(Admin dashboard)
function(Display collection\npoints' status)
feature(Display dumpsters'\navailability)
activity(Read dumpsters' digital twins)
task(Invoke availability API)
task(Check for issues)
feature(Display dumpsters'\noccupied volume)
activity(Read dumpsters' digital twins)
task(Invoke volume API)
task(Check for issues)

function(Display trucks'\nreal time status)
feature(Display trucks'\nposition)
activity(Read trucks'\ndigital twin,)
activity(Update trucks'\nposition on the map,)
feature(Display trucks'\ncarried waste)
activity(Read trucks'\ndigital twin,)
activity(Update trucks'\nreal time occupied volume,)

function(Display complaints)
feature(Display list of complaints)
activity(Read complaints\nfrom database,)

function(Register new citizens)
feature(Create smart-cards\nfor new citizens)
activity(Create API for citizen creation)
task(Insert citizen name)
task(Insert citizen address)


@endwbs