@startwbs
!include ../metamodels/work-breakdown.iuml
!define title TR

requirement(Trucks routing)

function(Plan ordinary waste\ndisposal missions)
feature(Notify when a\ndumpster is full)
activity(Detect occupied volume\nafter every disposal,)
activity(Create trucks' digital twin,)
activity(Update digital twin status, )
activity(Send notification to server)
task(Send dumpster ID)
task(Find first available\ntruck for the mission)
feature(Look for other dumpsters to\ncollect near the full one)
activity(Find position of full dumpster,)
activity(Find almost full dumpsters\nnear the full one,)
feature(Calculate best route)
activity(Implement Dijkstra's algorithm,)
activity(Send route to the truck,)
activity(Update truck's digital twin,)
feature(Track trucks'\nreal time position)
activity(Provide trucks\nwith GPS sensor,)
activity(Update trucks' digital twin,)

function(Plan extraordinary waste\ndisposal missions)
feature(Notify when a request\nis submitted)
activity(Send notification to server)
task(Send address and type\nof waste of the mission)
task(Find first available\ntruck for the mission)
feature(Group missions\nby type of waste)
activity(Find other requests with same type of waste,)
activity(Try to satisfy the requests in a single mission,)
feature(Calculate best route)
activity(Implement Dijkstra's algorithm,)
activity(Send route to the truck,)
activity(Update truck's digital twin,)
feature(Track trucks'\nreal time position)
activity(Provide trucks\nwith GPS sensor,)
activity(Update trucks' digital twin,)

@endwbs