@startwbs
!include ../metamodels/work-breakdown.iuml

requirement(Admin dashboard)
function(Display collection\npoints' status)
feature(Display dumpsters'\navailability)
feature(Display dumpsters'\noccupied volume)

function(Display trucks'\nreal time status)
feature(Display trucks'\nposition)
feature(Display trucks'\ncarried waste)

function(Display complaints)
feature(Display list of complaints)

function(Register new citizens)
feature(Create smart-cards\nfor new citizens)

@endwbs