@startuml Requirement Breakdown Structure
<style>
wbsDiagram {
    .goals .requirements .functions .features {
        LineColor #000000
        RoundCorner 10
        Shadowing 0.0
    }
    .goals {
        BackgroundColor #4D96FF
    }
    .requirements {
        BackgroundColor #6BCB77
    }
    .functions {
        BackgroundColor #FFD93D
    }
    .features {
        BackgroundColor #FF6B6B
    }
}
</style>
!unquoted procedure goal($name)
* $name <<goals>>
!endprocedure
'
!unquoted procedure requirement($name)
** $name <<requirements>>
!endprocedure
'
!unquoted procedure function($name)
*** $name <<functions>>
!endprocedure
'
!unquoted procedure feature($name)
**** $name <<features>>
!endprocedure
@enduml