@startuml Work Breakdown Structure
<style>
wbsDiagram {
    .requirements .functions .features .activities .tasks {
        LineColor #000000
        RoundCorner 10
        Shadowing 0.0
    }
    .requirements {
        BackgroundColor #85C88A
    }
    .functions {
        BackgroundColor #EBD671
    }
    .features {
        BackgroundColor #EEEEEE
    }
    .activities {
        BackgroundColor #CDDEFF
    }
    .tasks {
        BackgroundColor #FFFFFF
    }
}
</style>
'
!$counter = 1
'
!unquoted procedure requirement($name)
* $name <<requirements>>
!endprocedure
'
!unquoted procedure function($name)
** $name <<functions>>
!endprocedure
'
!unquoted procedure feature($name)
*** $name <<features>>
!endprocedure
'
!unquoted procedure activity($name)
**** $name <<activities>>
!endprocedure
'
!unquoted procedure activity($name, $increment)
**** [$title-$counter]\n$name <<activities>>
!$counter = $counter + 1
!endprocedure
'
!unquoted procedure task($name)
***** [$title-$counter]\n$name <<tasks>>
!$counter = $counter + 1
!endprocedure
'
legend right
    Green = Requirement
    Yellow = Function
    Grey = Feature
    Light Blue = Activity
    White = Task
endlegend
@enduml