name: Generate Appendix

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-plantuml-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Generate PlantUml Images
        uses: grassedge/generate-plantuml-action@master
        with:
          path: uml
          message: "docs(uml): render plantuml diagrams"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Appendix
        run: |
          chmod 777 doc/appendix/*.sh
          ./doc/appendix/generate-appendix.sh