name: Generate Appendix

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  generate-plantuml-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg uml/
      - name: Generate Appendix
        run: ./doc/appendix/generate-appendix.sh
        shell: bash
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Generate SVG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
