name: Generate Appendix

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  generate-plantuml-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg uml/*.puml
      - name: Setting up node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Add node-plantuml
        run: npm i -g node-plantuml
        shell: bash
      - name: Generate PlantUml Images
        run: |
          find uml/ -type f -name "*.puml" > files.txt
          while read file; do
            NAME=$(echo "$file" | cut -f 1 -d '.')
            puml generate "$file" -o "$NAME.png"
          done < files.txt
          rm files.txt
        shell: bash
      - name: Generate Appendix
        run: ./doc/appendix/generate-appendix.sh
        shell: bash
      - name: Commit Changes
        if: github.actor == 'SimoneRomagnoli'
        run: |
          git config --global user.email "simone.romagnoli10@studio.unibo.it"
          git config --global user.name "SimoneRomagnoli"
          git add uml/
          git commit -m "docs(uml): render plantuml diagrams"
          git add doc/appendix/appendix.tex
          git commit -m "docs(tex): generate appendix"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SR_API_GITHUB_TOKEN }}
      - name: Commit Changes
        if: github.actor == 'alessandro-marcantoni'
        run: |
          git config --global user.email "alessandr.marcanton2@studio.unibo.it"
          git config --global user.name "alessandro-marcantoni"
          git add uml/
          git commit -m "docs(uml): render plantuml diagrams"
          git add doc/appendix/appendix.tex
          git commit -m "docs(tex): generate appendix"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.AM_API_GITHUB_TOKEN }}
