name: Generate Appendix

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  generate-plantuml-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Generate PNG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tpng uml/*.puml -o ../img/
      - name: Generate Appendix
        run: ./.github/scripts/generate-appendix.sh
        shell: bash
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "docs(uml): generate PNG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
