name: Generate Appendix

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  generate-plantuml-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tsvg uml/*.puml
      - name: Setting up node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Add node-plantuml
        run: npm i -g node-plantuml
        shell: bash
      - name: Generate PlantUml Images
        run: |
          find uml/ -type f -name "*.puml" > files.txt
          while read file; do
            NAME=$(echo "$file" | cut -f 1 -d '.')
            puml generate "$file" -o "$NAME.png"
          done < files.txt
          rm files.txt
        shell: bash
      - name: Generate Appendix
        run: ./doc/appendix/generate-appendix.sh
        shell: bash
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Generate SVG files for PlantUML diagrams"
          branch: ${{ github.head_ref }}
