name: Generate Appendix

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-plantuml-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Generate PlantUml Images
        uses: grassedge/generate-plantuml-action@master
        with:
          path: uml
          message: "docs(uml): render plantuml diagrams"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Appendix
        if: github.actor == 'SimoneRomagnoli'
        run: |
          ./doc/appendix/generate-appendix.sh
          git config --global user.email "simone.romagnoli10@studio.unibo.it"
          git config --global user.name "SimoneRomagnoli"
          git add doc/appendix/appendix.tex
          git commit -m "docs: generate appendix"
          if git status | grep -q "Changes not staged for commit"
          then 
            git add uml/
            git commit -m "ci: rename .pm.puml to .puml"
          fi
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SR_API_GITHUB_TOKEN }}
      - name: Generate Appendix
        if: github.actor == 'alessandro-marcantoni'
        run: |
          chmod 777 doc/appendix/*.sh
          ./doc/appendix/generate-appendix.sh
          git config --global user.email "alessandr.marcanton2@studio.unibo.it"
          git config --global user.name "alessandro-marcantoni"
          git add doc/appendix/appendix.tex
          git commit -m "docs: generate appendix"
          if git status | grep -q "Changes not staged for commit"
          then 
            git add uml/
            git commit -m "ci: rename .pm.puml to .puml"
          fi
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.AM_API_GITHUB_TOKEN }}
